version: "3"
services:
  app-outside:
    build: 
      context: .
      dockerfile: ./backend-outside/Dockerfile
    ports:
      - "5001:5000"
    container_name: app-outside
    volumes:
      - ./backend-outside:/usr/src/app
      - ./frontend:/usr/src/frontend
    command: flask run --host=0.0.0.0
  app-auth:
    build: 
      context: .
      dockerfile: ./backend-auth/Dockerfile
    ports:
      - "6001:6000"
    container_name: app-auth
    volumes:
      - ./backend-auth:/usr/src/app
    command: flask run --host=0.0.0.0