version: "3.8"

services:
  myapp:
    build: ./app
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    ports:
      - "5000:5000"
    networks:
      - my_network
    volumes:
    - ./app/flask-tutorial:/app
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql    
  myapp-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx/
    # Nginxコンテナが起動される前にFlaskアプリケーションが起動される
    depends_on:
      - myapp
    networks:
      - my_network
    depends_on:
      - mysql    
    networks:
      - my_network
  # [mysql]
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my_network
  # [phpmyadmin] 開発環境専用
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-web_app
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    networks:
      - my_network      
networks:
  my_network: