version: "3.8"

services:
  myapp:
    build: ./app
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    ports:
      - "5000:5000"
    networks:
      - my_network
  myapp-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx/
    # Nginxコンテナが起動される前にFlaskアプリケーションが起動される
    depends_on:
      - myapp
    networks:
      - my_network
networks:
  my_network: