version: "3"
services:
  app:
    build: ./app
    volumes:
      - socket:/tmp
      - type: bind
        source: ./app/flaskapp
        target: /app
    command: uwsgi --ini /app/app.ini

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp

volumes:
  socket: