version: "3.8"

services:
  myapp:
    build: ./app
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    ports:
      - "5000:5000"

  nginx:
    build: ./web
    container_name: ${WEB_SERVER_CONTAINER_NAME}
    restart: always
    ports:
      - "80:80"
